services:
  liquibase-migrations:
    container_name: migrations_travel_planner
    image: liquibase/liquibase:4.29
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5438/travelPlannerDB
      - --username=${DB_USERNAME}
      - --password=${DB_PASSWORD}
      - update
    volumes:
      - ./migrations:/changesets

  postgresql:
    image: postgres:17
    container_name: postgresTravelPlanner
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: travelPlannerDB
      PGPORT: 5438
    ports:
      - "5438:5438"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  auth-service:
    build:
      context: .
      dockerfile: auth/Dockerfile
    container_name: auth_service
    depends_on:
      - postgresql
      - liquibase-migrations
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5438/travelPlannerDB
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8081:8080"

  planner-service:
    build:
      context: .
      dockerfile: planner/Dockerfile
    container_name: planner_service
    depends_on:
      - postgresql
      - liquibase-migrations
      - auth-service
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5438/travelPlannerDB
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      AUTH_SERVICE_URL: http://auth-service:8080
    ports:
      - "8082:8080"

  external-service:
    build:
      context: .
      dockerfile: external/Dockerfile
    container_name: external_service
    depends_on:
      - postgresql
      - liquibase-migrations
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5438/travelPlannerDB
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8083:8080"

  library-service:
    build:
      context: .
      dockerfile: library/Dockerfile
    container_name: library_service
    depends_on:
      - postgresql
      - liquibase-migrations
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5438/travelPlannerDB
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "8084:8080"

volumes:
  postgres_data:
