services:
  postgresql:
    image: postgres:17
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: travelPlannerDB
      PGPORT: 5438
    ports:
      - "5438:5438"
    volumes:
      - /home/deploy/postgres_data:/var/lib/postgresql/data

  liquibase-migrations:
    image: liquibase/liquibase:4.29
    env_file:
      - .env
    depends_on:
      - postgresql
    command:
      - --searchPath=/changesets
      - --changelog-file=master.xml
      - --driver=org.postgresql.Driver
      - --url=jdbc:postgresql://postgresql:5438/travelPlannerDB
      - --username=postgres
      - --password=postgres
      - update
    volumes:
      - /home/deploy/travel-planner-backend/migrations:/changesets
    deploy:
      restart_policy:
        condition: none

  auth-service:
    image: ghcr.io/slash0t/putevod-auth:latest
    env_file:
      - .env
    depends_on:
      - postgresql
      - liquibase-migrations
    ports:
      - "8081:8081"
    deploy:
      update_config:
        order: start-first

  planner-service:
    image: ghcr.io/slash0t/putevod-planner:latest
    env_file:
      - .env
    depends_on:
      - postgresql
      - liquibase-migrations
      - auth-service
    ports:
      - "8082:8082"
    deploy:
      update_config:
        order: start-first

  external-service:
    image: ghcr.io/slash0t/putevod-external:latest
    env_file:
      - .env
    depends_on:
      - postgresql
      - liquibase-migrations
    ports:
      - "8083:8083"
    deploy:
      update_config:
        order: start-first

  library-service:
    image: ghcr.io/slash0t/putevod-library:latest
    env_file:
      - .env
    depends_on:
      - postgresql
      - liquibase-migrations
    ports:
      - "8084:8084"
    deploy:
      update_config:
        order: start-first

volumes:
  postgres_data:
