server:
  port: ${SERVER_PORT_EXTERNAL}

app:
  external-api:
    openTripMapApiKey: ${OPENTRIPMAP_API_KEY}
    openTripMapBaseUrl: ${OPENTRIPMAP_BASE_URL}
    yandexGeoSuggestApiKey: ${YANDEX_GEOSUGGEST_API_KEY}
    yandexGeoSuggestBaseUrl: ${YANDEX_GEOSUGGEST_BASE_URL}
    yandex-geocoder-api-key: ${YANDEX_GEOCODER_API_KEY}
    yandex-geocoder-base-url: ${YANDEX_GEOCODER_BASE_URL}
  yandex:
    gpt:
      api-key: ${YANDEX_GPT_API_KEY}
      folder-id: ${YANDEX_GPT_FOLDER_ID}
      api-url: https://llm.api.cloud.yandex.net/foundationModels/v1/completion
      max-tokens: "1000"
      temperature: 0.7

logging:
  level:
    ru.putevod.app: DEBUG
    org.springdoc: DEBUG

spring:
  application:
    name: putevod-external-service
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  security:
    user:
      name: ${SPRING_SECURITY_USER}
      password: ${SPRING_SECURITY_PASSWORD}

services:
  auth:
    url: ${AUTH_SERVICE_URL}

springdoc:
  api-docs:
    path: /api-docs-external
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: list
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    csrf:
      enabled: false
  packages-to-scan: ru.putevod.app.external.controller
  paths-to-match: /api/v1/**

auth:
  token: ${AUTH_SERVICE_TOKEN:service_token_for_development}
