server:
  port: 8081

app:
  external-api:
    openTripMapApiKey: 5ae2e3f221c38a28845f05b6eef345b7956e84e655924ecd1cdf1ca2
    openTripMapBaseUrl: https://api.opentripmap.com/0.1/

logging:
  level:
    ru.putevod.app: DEBUG

spring:
  application:
    name: travel-planner-external-service

  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
      - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

services:
  auth:
    url: http://localhost:8080/api/v1

auth:
  token: ${AUTH_SERVICE_TOKEN:service_token_for_development}
