server:
  port: ${SERVER_PORT_AUTH}

spring:
  application:
    name: putevod-auth-service
  config:
    import: optional:file:.env[.properties]
  security:
    user:
      name: ${SPRING_SECURITY_USER:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin}
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/travelPlannerDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${HIKARI_MAX_POOL_SIZE:5}
      minimum-idle: ${HIKARI_MIN_IDLE:2}
      connection-timeout: 10000
      idle-timeout: 180000
      max-lifetime: 300000
      leak-detection-threshold: 30000
      connection-test-query: SELECT 1
      validation-timeout: 5000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    open-in-view: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha
    disable-swagger-default-url: true
    display-request-duration: true
    doc-expansion: list
    default-models-expand-depth: 1
    default-model-expand-depth: 1
    csrf:
      enabled: false
  packages-to-scan: ru.putevod.app.auth.controller
  default-produces-media-type: application/json
  default-consumes-media-type: application/json

logging:
  level:
    org.springframework.web: INFO
    ru.putevod.app.auth: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG

app:
  frontend-url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET:secretsecretsecretsecretsecretsecretsecretsecret}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}
    anonymous-token-expiration-ms: ${JWT_ANONYMOUS_TOKEN_EXPIRATION_MS}
  email:
    from: ${EMAIL_FROM}
  verification-token-expiration-hours: 24
  reset-token-expiration-minutes: 15
  auth-token: ${AUTH_SERVICE_TOKEN:service_token_for_development}
