server:
  port: ${SERVER_PORT_AUTH}

spring:
  application:
    name: putevod-auth-service
  config:
    import: optional:file:.env[.properties]
  security:
    user:
      name: ${SPRING_SECURITY_USER:admin}
      password: ${SPRING_SECURITY_PASSWORD:admin}
  liquibase:
    enabled: false
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5438/travelPlannerDB}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  frontend-url: ${FRONTEND_URL}
  jwt:
    secret: ${JWT_SECRET:secretsecretsecretsecretsecretsecretsecretsecret}
    access-token-expiration-ms: ${JWT_ACCESS_TOKEN_EXPIRATION_MS}
    refresh-token-expiration-ms: ${JWT_REFRESH_TOKEN_EXPIRATION_MS}
    anonymous-token-expiration-ms: ${JWT_ANONYMOUS_TOKEN_EXPIRATION_MS}
  email:
    from: ${EMAIL_FROM}
  verification-token-expiration-hours: 24
  reset-token-expiration-minutes: 15
  auth-token: ${AUTH_SERVICE_TOKEN:service_token_for_development}