server:
  port: 8080
  servlet:
    context-path:

spring:
  application:
    name: auth-service
  liquibase:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5438/travelPlannerDB
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: nikelodeon53@gmail.com
    password: kjez szkp lfpx ptrm
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

app:
  frontend-url: https://travelplanner.com
  jwt:
    secret: ${JWT_SECRET:YgUH7tDfJVRgH3Kvd9oNaX1PYqIj0yGGM2rHDouD9zL7rAp8HOt8XbX9UQ2q1QQjA9QacCXCqoSXMQIPT8EGJ92kUuG7zGuKvBbD}
    access-token-expiration-ms: 3600000000
    refresh-token-expiration-ms: 604800000
    anonymous-token-expiration-ms: 1800000
  email:
    from: nikelodeon53@gmail.com